// POINTING

#define ANALOG_JOYSTICK_X_AXIS_PIN A5
#define ANALOG_JOYSTICK_Y_AXIS_PIN A4

#define POINTING_DEVICE_INVERT_X TRUE
#define POINTING_DEVICE_INVERT_Y TRUE
#define ANALOG_JOYSTICK_SPEED_REGULATOR 10


#include_next "config.h"
